# Email Server Settings
imap_server: imap.gmail.com
email_address: garvgdsc@gmail.com
password:  # For Gmail, use App Password

# Folder Settings
scan_folder: INBOX
suspicious_folder: Suspicious

# Model Settings
threshold: 0.5  # Probability threshold for flagging emails as suspicious
model_path: phishing_model.pkl
vectorizer_path: vectorizer.pkl 